# config/config.py

# ----------------------------
# Application
# ----------------------------
APP_NAME = "The Chaanakya"
APP_DESCRIPTION = "Agentic Legal Reasoning Assistant"

# ----------------------------
# Ollama Configuration
# ----------------------------
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL_NAME = "llama3.1"

# ----------------------------
# LLM Parameters
# ----------------------------
TEMPERATURE = 0.2
MAX_TOKENS = 1024
TOP_P = 0.9

# ----------------------------
# Conversation Memory
# ----------------------------
MAX_CONVERSATION_TURNS = 10
SESSION_STATE_KEY = "chaanakya_sessions"

# ----------------------------
# Web Search Configuration
# ----------------------------
SEARCH_RESULTS_LIMIT = 5

ALLOWED_LEGAL_DOMAINS = [
    "indiankanoon.org",
    "scobserver.in",
    "lawmin.gov.in",
    "supremecourtofindia.nic.in",
    "legislative.gov.in",
    "gov.in",
]

# ----------------------------
# Safety & Guardrails
# ----------------------------
ENABLE_WEB_SEARCH = True
ENABLE_DISCLAIMER = True

LEGAL_DISCLAIMER = (
    "⚠️ Disclaimer: This response is generated by an AI system for "
    "informational purposes only and does not constitute professional "
    "legal advice. Please consult a qualified legal professional for "
    "advice specific to your situation."
)
